### ISSUE TITLE
DNS Enumeration Failing

### ISSUE THREAD

**Issue by ashishgajjar90** [thewhiteh4t/FinalRecon#13]
I just installed this tool, and upon testing, I get the below error when trying to run a --full scan against any URL:

[!] Starting DNS Enumeration...

Traceback (most recent call last):
  File "finalrecon.py", line 224, in <module>
    full_recon()
  File "finalrecon.py", line 159, in full_recon
    dnsrec(domain, output, data)
  File "/Tools/FinalRecon/modules/dns.py", line 19, in dnsrec
    pkt = q.send('8.8.8.8', 53, tcp='UDP')
  File "/usr/lib/python3/dist-packages/dnslib/dns.py", line 365, in send
    sock.connect((dest,port))
ConnectionRefusedError: [Errno 111] Connection refused

Help?

**Comment by thewhiteh4t** [comment]
@ashishgajjar90 as per the error, it is unable to connect at `8.8.8.8` for some reason

**Comment by ashishgajjar90** [comment]
Is that DNS IP hard coded within the config files? Or is it picking that DNS server from my network settings? I tried specifying a DNS server manually, but I still get the same error.

How can we troubleshoot more and get a fix for this?

**Comment by thewhiteh4t** [comment]
@ashishgajjar90 it's hard coded, when I was testing with cloudflare dns I got the same error so I hard coded google dns

**Comment by ashishgajjar90** [comment]
So how do we troubleshoot the connection issue?

Thanks & Regards

Ashish Gajjar

**Comment by ashishgajjar90** [comment]
I use both Google and Cloudflare DNS in my network and those are fine. The script for some reason isn't :/

**Comment by thewhiteh4t** [comment]
@ashishgajjar90 take a look at this https://serverfault.com/questions/964540/port-53-udp-and-tcp-gets-blocked-when-openvpn-is-operating

**Comment by chr0n1k** [comment]
I am getting the same error and verified on my end that I can reach the required ports:

**nc -v -u 8.8.8.8 53**
_dns.google [8.8.8.8] 53 (domain) open_

**Comment by chr0n1k** [comment]
I used an alternate DNS server in the **dns.py** module and it worked. Seems like Google is blocking such requests maybe?

**Comment by thewhiteh4t** [comment]
@chr0n1k that does look like google is blocking but then it should block every such request, like if I use dns enum module it should block me too but it doesn't, strange

**Comment by chr0n1k** [comment]
@thewhiteh4t I used the dns enum module specifically to recreate the issue. It is strange that I could port knock with netcat but when running dns enum it threw that error. I tried the same with 1.1.1.1 and got the same error. Then used a regional DNS server and it worked.

**Comment by thewhiteh4t** [comment]
@chr0n1k the error is actually in dns.py which is a part of dnslib
```
pkt = q.send('8.8.8.8', 53, tcp='UDP')
File "/usr/lib/python3/dist-packages/dnslib/dns.py", line 365, in send
sock.connect((dest,port))
ConnectionRefusedError: [Errno 111] Connection refused
```
and connection is refused before it can send anything, if nothing is sent then why will google or cloudflare block the connection

**Comment by chr0n1k** [comment]
@thewhiteh4t I started my investigation there then when I tested an alternate DNS server in the dns.py module it worked. Don't know how else this error would be caused.

**Comment by thewhiteh4t** [comment]
@chr0n1k I will try to change implementation if it's possible

**Comment by chr0n1k** [comment]
@thewhiteh4t That would be great. or parse a DNS variable option. Though that can be a nightmare too.

**Comment by thewhiteh4t** [comment]
@chr0n1k yeah, this needs a proper solution

**Comment by thewhiteh4t** [comment]
@chr0n1k 
can you please test this code : 
```
#!/usr/bin/env python3

import dns.resolver           #pip3 install dnspython

addr = 'secure-startup.com'
dmarc_addr = '_dmarc.' + addr

types = ['A', 'AAAA', 'ANY', 'CAA', 'CNAME', 'MX', 'NS', 'TXT']

for qtype in types:
    try:
        ans = dns.resolver.query(addr, qtype)
        for item in ans:
            print(addr + '\t' + qtype + '\t' + str(item))
        print()
    except Exception as e:
        #print(e)
        pass

try:
    ans = dns.resolver.query(dmarc_addr, 'TXT')
    for item in ans:
        print(dmarc_addr + '\t' + 'TXT' + '\t' + str(item))
except Exception as e:
    print(e)
```

**Comment by thewhiteh4t** [comment]
Closing due to inactivity.

**Comment by mmuncan** [comment]
i ha the same error, when i was connected to my VPN. i changed the ip in the file from Google to Cloudfare, that is from 8.8.8.8 to 1.1.1.1 on two locations.

After that it worked :D

**Comment by thewhiteh4t** [comment]
@mmuncan can you test the code I have given above? With and without vpn, if it works for you in both cases then I can update

**Comment by JavuMan** [comment]
@thewhiteh4t i test your code and i have no issue (VPN on with DNS exclusive ans VPN off).
Error is in app of VPN who exclusive DNS on (ExpressVPN).
Now DNS Enumeration work for me.

**Comment by thewhiteh4t** [comment]
@JavuMan thanks for testing, should I will implement new code soon!
