### ISSUE TITLE
json.decoder.JSONDecodeError

### ISSUE THREAD

**Issue by mehedi1194** [thewhiteh4t/FinalRecon#16]
### Facing this Error

[!] Starting Sub-Domain Enumeration...

[!] Requesting ThreadCrowd
[!] Requesting crt.sh
[!] Requesting AnubisDB
[!] Requesting BuffOver
[!] Requesting ThreatMiner
Traceback (most recent call last):
  File "finalrecon.py", line 227, in <module>
    full_recon()
  File "finalrecon.py", line 164, in full_recon
    subdomains(domain, tout, output, data)
  File "/root/Tool/Recon/Framework/FinalRecon/modules/subdom.py", line 166, in subdomains
    loop.run_until_complete(query(hostname, tout))
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/root/Tool/Recon/Framework/FinalRecon/modules/subdom.py", line 155, in query
    fb_cert(hostname, tout)
  File "/root/Tool/Recon/Framework/FinalRecon/modules/subdom.py", line 126, in fb_cert
    json_load = json.loads(json_read)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 355, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Expecting ',' delimiter: line 4 column 40 (char 69)

![2020-05-01_16-00](https://user-images.githubusercontent.com/54717234/80797966-f8aa9080-8bc4-11ea-997e-bf6b1aa44884.png)

**Comment by Dicer-TDP** [comment]
Your installation has not complete, bro. Please check back!

**Comment by thewhiteh4t** [comment]
@mehedi1194 are you getting this error on every domain or just a specific one?

**Comment by thewhiteh4t** [comment]
@mehedi1194 check `keys.json` file, I think you have not entered the key properly

**Comment by thewhiteh4t** [comment]
Closing due to inactivity.

**Comment by repeattrick** [comment]
what is the format to enter key properly in keys.json

**Comment by thewhiteh4t** [comment]
@repeattrick 
https://github.com/thewhiteh4t/FinalRecon#facebook-developers-api
replace `null` with key in the format given above
