### ISSUE TITLE
Issues with missing whois module

### ISSUE THREAD

**Issue by antihackme** [thewhiteh4t/FinalRecon#2]
Successfully built ipaddr
Installing collected packages: ipaddr, ipwhois
Successfully installed ipaddr-2.2.0 ipwhois-1.1.0
┌─[antihack@parrot]─[~/FinalRecon]
└──╼ $python3 finalrecon.py
Traceback (most recent call last):
  File "finalrecon.py", line 9, in <module>
    from modules.whois import whois_lookup
  File "/home/antihack/FinalRecon/modules/whois.py", line 3, in <module>
    import ipwhois
ModuleNotFoundError: No module named 'ipwhois'
┌─[✗]─[antihack@parrot]─[~/FinalRecon]
└──╼ $python3 finalrecon.py -h
Traceback (most recent call last):
  File "finalrecon.py", line 9, in <module>
    from modules.whois import whois_lookup
  File "/home/antihack/FinalRecon/modules/whois.py", line 3, in <module>
    import ipwhois
ModuleNotFoundError: No module named 'ipwhois'

**Comment by thewhiteh4t** [comment]
@antihackme did you execute `pip install` in place of `pip3 install` by mistake? i will test on parrot just to be sure

**Comment by thewhiteh4t** [comment]
@antihackme tested in parrotsec os, its working fine for me no errors

**Comment by thewhiteh4t** [comment]
Closing due to inactivity.

**Comment by KumarAtulJaiswal** [comment]
hahaha, my mistake.. i accidentally installed a  ' pip -r requirements.txt  ' instead of  '  pip3  -r requirements.txt  '
