### ISSUE TITLE
Too many open files on Ubuntu 20.04

### ISSUE THREAD

**Issue by mark0100** [thewhiteh4t/FinalRecon#27]
If i run finalrecon.py (with --full) I get "OSError: [Errno 24] Too many open files" exceptions in:
 - File "<homedir>/FinalRecon/modules/portscan.py", line 44, in sock_conn
 - File "/usr/lib/python3.8/threading.py", line 870

Here is part of the errors:
************************************ start logging ******************************************
  File "/home/mark/FinalRecon/modules/portscan.py", line 44, in sock_conn
  File "/home/mark/FinalRecon/modules/portscan.py", line 44, in sock_conn
  File "/home/mark/FinalRecon/modules/portscan.py", line 44, in sock_conn
    s.close()
    s.close()
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
OSError: [Errno 24] Too many open files

During handling of the above exception, another exception occurred:

    self.run()
UnboundLocalError: local variable 's' referenced before assignment
    self._target(*self._args, **self._kwargs)
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/home/mark/FinalRecon/modules/portscan.py", line 44, in sock_conn
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self._target(*self._args, **self._kwargs)
  File "/home/mark/FinalRecon/modules/portscan.py", line 44, in sock_conn
    s.close()
  File "/usr/lib/python3.8/threading.py", line 870, in run
  File "/home/mark/FinalRecon/modules/portscan.py", line 44, in sock_conn
UnboundLocalError: local variable 's' referenced before assignment
    self._target(*self._args, **self._kwargs)
  File "/home/mark/FinalRecon/modules/portscan.py", line 44, in sock_conn
  File "/usr/lib/python3.8/threading.py", line 870, in run
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
OSError: [Errno 24] Too many open files
    self._target(*self._args, **self._kwargs)
    self.run()
    self._target(*self._args, **self._kwargs)
  File "/home/mark/FinalRecon/modules/portscan.py", line 44, in sock_conn
    s.close()
UnboundLocalError: local variable 's' referenced before assignment
    s.close()
UnboundLocalError: local variable 's' referenced before assignment
  File "/usr/lib/python3.8/socket.py", line 231, in __init__
  File "/usr/lib/python3.8/socket.py", line 231, in __init__
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
UnboundLocalError: local variable 's' referenced before assignment
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
  File "/usr/lib/python3.8/threading.py", line 870, in run
UnboundLocalError: local variable 's' referenced before assignment
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.8/threading.py", line 870, in run
  File "/home/mark/FinalRecon/modules/portscan.py", line 44, in sock_conn
OSError: [Errno 24] Too many open files
    s.close()
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
  File "/usr/lib/python3.8/threading.py", line 870, in run
  File "/home/mark/FinalRecon/modules/portscan.py", line 44, in sock_conn
  File "/home/mark/FinalRecon/modules/portscan.py", line 44, in sock_conn
    self._target(*self._args, **self._kwargs)
    self.run()
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    _socket.socket.__init__(self, family, type, proto, fileno)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
    self.run()
    s.close()
    self._target(*self._args, **self._kwargs)
    _socket.socket.__init__(self, family, type, proto, fileno)
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
  File "/usr/lib/python3.8/threading.py", line 870, in run
    s.close()
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 870, in run
UnboundLocalError: local variable 's' referenced before assignment
  File "/home/mark/FinalRecon/modules/portscan.py", line 44, in sock_conn
OSError: [Errno 24] Too many open files
*********************************** end logging *********************************************
I'm on Ubuntu 20.04:
- uname -a:
Linux <hostname> 5.4.0-51-generic #56-Ubuntu SMP Mon Oct 5 14:28:49 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by thewhiteh4t** [comment]
@mark0100 please share output of `ulimit -n`

**Comment by mark0100** [comment]
ulimit -n --> 1024

**Comment by thewhiteh4t** [comment]
@mark0100 thats weird, i have `1024` too, if i reduce it to lets say `256` I get the same error, but not with `1024`, which FinalRecon version are you on? latest is `1.0.8`

**Comment by mark0100** [comment]
I'm on 1.0.8 too:
"FinalRecon - The Last Recon Tool You Will Need | v1.0.8" 

Maybe i have more files open with other open applications. Or is the 1024 a per session limit?!?

If i increase the limit to 2048 it looks ok.
