### ISSUE TITLE
threading error

### ISSUE THREAD

**Issue by r0bag** [thewhiteh4t/FinalRecon#30]
Hi,

upon running the program I receive the following error:
Traceback (most recent call last):
  File "finalrecon.py", line 272, in <module>
    full_recon()
  File "finalrecon.py", line 213, in full_recon
    ps(ip, output, data)
  File "/opt/FinalRecon/modules/portscan.py", line 23, in ps
    t.start()
  File "/usr/lib/python3.7/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread
kali@kali:/opt/FinalRecon# python3 --version
Python 3.7.5

Can you advise on this?
Thanks.

**Comment by thewhiteh4t** [comment]
@r0bag 
which distro?
did portscan work before this? or this is the issue on first run itself?
please share output of `ulimit -n`

**Comment by r0bag** [comment]
kali@kali:~# uname -a
Linux kali 5.7.0-kali1-686-pae #1 SMP Debian 5.7.6-1kali2 (2020-07-01) i686 GNU/Linux
kali@kali:~# ulimit -n
1024

and it fails exactly at this step on the first run:

[!] Starting Port Scan...

[+] Testing Top 1000 Ports...

[+] 22     ssh
[+] 80     http
Traceback (most recent call last):
  File "finalrecon.py", line 272, in <module>
    full_recon()
  File "finalrecon.py", line 213, in full_recon
    ps(ip, output, data)
  File "/opt/FinalRecon/modules/portscan.py", line 23, in ps
    t.start()
  File "/usr/lib/python3.7/threading.py", line 852, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

**Comment by thewhiteh4t** [comment]
@r0bag please try changing the ulimit value to `2048` using the command `ulimit -n 2048` and try running finalrecon after this

**Comment by r0bag** [comment]
Thanks, now it works!
