### ISSUE TITLE
error after updating in KALI

### ISSUE THREAD

**Issue by foo2rama** [thewhiteh4t/FinalRecon#33]
Tool looks great and seems to automate things in a great way, but alas I am throwing these errors.

Kali is fully upgraded via apt upgrade and dist-upgrade as of today, running apt upgrade finalupdate reports all is 'finalrecon is already the newest version (0~20201111-0kali1)'

`[!] Starting Sub-Domain Enumeration...

[!] Requesting BuffOver
[!] Requesting ThreadCrowd
[!] Requesting crt.sh
[!] Requesting AnubisDB
[!] Requesting ThreatMiner
Traceback (most recent call last):
  File "/usr/bin/finalrecon", line 265, in <module>
    full_recon()
  File "/usr/bin/finalrecon", line 199, in full_recon
    subdomains(domain, tout, output, data)
  File "/usr/share/finalrecon/modules/subdom.py", line 166, in subdomains
    loop.run_until_complete(query(hostname, tout))
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/share/finalrecon/modules/subdom.py", line 149, in query
    await asyncio.gather(
  File "/usr/share/finalrecon/modules/subdom.py", line 123, in fb_cert
    with open('conf/keys.json', 'r') as keyfile:
FileNotFoundError: [Errno 2] No such file or directory: 'conf/keys.json'
`

**Comment by thewhiteh4t** [comment]
@foo2rama I am aware of this issue and I have fixed it in v1.1.2 but the kali version is 1.1.0, it will be updated soon until then you can git clone it

**Comment by foo2rama** [comment]
Awesome thank you! I will resolve that way.

**Comment by thewhiteh4t** [comment]
@foo2rama it has been updated to new version in kali, closing,
