### ISSUE TITLE
dns enumeration failing

### ISSUE THREAD

**Issue by nigamelastic** [thewhiteh4t/FinalRecon#37]
while running it with --full option using kali 2020.4, the script fails at dns enumeration step with the following error:

[!] Starting DNS Enumeration...

Traceback (most recent call last):
  File "/home/kali/Desktop/repos/FinalRecon/finalrecon.py", line 275, in <module>
    full_recon()
  File "/home/kali/Desktop/repos/FinalRecon/finalrecon.py", line 207, in full_recon
    dnsrec(domain, output, data)
  File "/home/kali/Desktop/repos/FinalRecon/modules/dns.py", line 19, in dnsrec
    pkt = q.send('8.8.8.8', 53, tcp='UDP')
  File "/usr/lib/python3/dist-packages/dnslib/dns.py", line 365, in send
    sock.connect((dest,port))
ConnectionRefusedError: [Errno 111] Connection refused

**Comment by thewhiteh4t** [comment]
@nigamelastic are you using a proxy or something like that?

**Comment by nigamelastic** [comment]
No , I am using it in virtual box in bridged mode, no.proxies

**Comment by thewhiteh4t** [comment]
@nigamelastic well as you know 8.8.8.8 is google dns and something is affecting the connection, try flushing dns cache, I tried --dns and its working for me so there is something going on in your configuration

**Comment by nigamelastic** [comment]
wow, you were absolutely correct, as soon as cleared the cache it worked, Thanks a lot
