### ISSUE TITLE
Log file not found

### ISSUE THREAD

**Issue by ShutdownRepo** [thewhiteh4t/FinalRecon#64]
After a fresh install, FinalRecon can't run. Issue brought with 2ff1202a4cbf37e67038ac5bbf2204221b7c5dd7
```
# finalrecon.py --help
Traceback (most recent call last):
  File "/opt/tools/FinalRecon/finalrecon.py", line 12, in <module>
    log_writer('Importing config...')
  File "/opt/tools/FinalRecon/modules/write_log.py", line 6, in log_writer
    logging.basicConfig(
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/logging/__init__.py", line 2050, in basicConfig
    h = FileHandler(filename, mode,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/logging/__init__.py", line 1181, in __init__
    StreamHandler.__init__(self, self._open())
                                 ^^^^^^^^^^^^
  File "/root/.pyenv/versions/3.11.5/lib/python3.11/logging/__init__.py", line 1213, in _open
    return open_func(self.baseFilename, self.mode,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/root/.local/share/finalrecon/run.log'
```

**Comment by thewhiteh4t** [comment]
@ShutdownRepo i have pushed a fix for this, please git pull and try again

**Comment by ShutdownRepo** [comment]
we're good
