### ISSUE TITLE
problem in --dir -w 

### ISSUE THREAD

**Issue by SanskarKashyap** [thewhiteh4t/FinalRecon#68]
it thrown exception in 

 finalrecon --dir --url http://saturn.picoctf.net:65203/ -w /usr/share/finalrecon/wordlists/dirb_small.txt
 
 
 finalrecon --dir --url http://saturn.picoctf.net:65203/ -w /usr/share/finalrecon/wordlists/dirb_big.txt

```
 ______  __   __   __   ______   __                                                                                                                                                          
/\  ___\/\ \ /\ "-.\ \ /\  __ \ /\ \                                                                                                                                                         
\ \  __\\ \ \\ \ \-.  \\ \  __ \\ \ \____                                                                                                                                                    
 \ \_\   \ \_\\ \_\\"\_\\ \_\ \_\\ \_____\                                                                                                                                                   
  \/_/    \/_/ \/_/ \/_/ \/_/\/_/ \/_____/                                                                                                                                                   
 ______   ______   ______   ______   __   __                                                                                                                                                 
/\  == \ /\  ___\ /\  ___\ /\  __ \ /\ "-.\ \                                                                                                                                                
\ \  __< \ \  __\ \ \ \____\ \ \/\ \\ \ \-.  \                                                                                                                                               
 \ \_\ \_\\ \_____\\ \_____\\ \_____\\ \_\\"\_\                                                                                                                                              
  \/_/ /_/ \/_____/ \/_____/ \/_____/ \/_/ \/_/                                                                                                                                              

[>] Created By   : thewhiteh4t
 |---> Twitter   : https://twitter.com/thewhiteh4t
 |---> Community : https://twc1rcle.com/
[>] Version      : 1.1.7

[+] Target : http://saturn.picoctf.net:65203

[+] IP Address : 13.59.203.175

[!] Starting Directory Enum...

[+] Threads          : 50
[+] Timeout          : 30
[+] Wordlist         : /usr/share/finalrecon/wordlists/dirb_big.txt
[+] Allow Redirects  : False
[+] SSL Verification : False
Traceback (most recent call last):
  File "/usr/bin/finalrecon", line 310, in <module>
    hammer(target, threads, tout, wdlist, redir, sslv, out_settings, data, filext)
  File "/usr/share/finalrecon/modules/dirrec.py", line 141, in hammer
    num_words = sum(1 for i in wordlist)
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/finalrecon/modules/dirrec.py", line 141, in <genexpr>
    num_words = sum(1 for i in wordlist)
                   ^^^^^^^^^^^^^^^^^^^^^
  File "<frozen codecs>", line 322, in decode
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xf3 in position 4382: invalid continuation byte

```

**Comment by SanskarKashyap** [comment]
exception is thrown in this wordlist only dirb_big.txt

**Comment by thewhiteh4t** [comment]
@SanskarKashyap thanks, it looks like the wordlists are not clean, I will add exception handling for this issue, in the meantime you can use `big.txt` from `seclists`

**Comment by hakkuri01** [comment]
@SanskarKashyap Most of the issues listed here in the Issues tab I've also noticed when using the tool, so I just went ahead and built the same tool concept from scratch and largely improved upon the concept here: https://github.com/hakkuri01/nokizaru
