### ISSUE TITLE
Using custom dns server via command line breaks

### ISSUE THREAD

**Issue by ppastorf** [thewhiteh4t/FinalRecon#74]
$ python3 finalrecon.py -nb --dns -d 8.8.8.8 --url https://github.com

```
[+] Target : https://github.com

[+] IP Address : 20.201.28.151

[!] Starting DNS Enumeration...

Traceback (most recent call last):
  File "/home/user/FinalRecon/finalrecon.py", line 292, in <module>
    dnsrec(hostname, dserv, out_settings, data)
  File "/home/user/FinalRecon/modules/dns.py", line 27, in dnsrec
    res.nameservers = dns_servers
    ^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/dns/resolver.py", line 1114, in nameservers
    raise ValueError(
ValueError: nameservers must be a list (not a <class 'str'>)
```

I tried multiple ways to pass a single dns server but it did not work properly

**Comment by thewhiteh4t** [comment]
@ppastorf fixed in https://github.com/thewhiteh4t/FinalRecon/commit/c407a97a6dce8095ab4aa800d0b1789921791aa6
`git pull` and test again :D
