### ISSUE TITLE
Traceback (most recent call last):

### ISSUE THREAD

**Issue by Eduard123321** [thewhiteh4t/FinalRecon#75]
python finalrecon.py --dns --url https://www.example.com 

 ______  __   __   __   ______   __
/\  ___\/\ \ /\ "-.\ \ /\  __ \ /\ \
\ \  __\\ \ \\ \ \-.  \\ \  __ \\ \ \____
 \ \_\   \ \_\\ \_\\"\_\\ \_\ \_\\ \_____\
  \/_/    \/_/ \/_/ \/_/ \/_/\/_/ \/_____/
 ______   ______   ______   ______   __   __
/\  == \ /\  ___\ /\  ___\ /\  __ \ /\ "-.\ \
\ \  __< \ \  __\ \ \ \____\ \ \/\ \\ \ \-.  \
 \ \_\ \_\\ \_____\\ \_____\\ \_____\\ \_\\"\_\
  \/_/ /_/ \/_____/ \/_____/ \/_____/ \/_/ \/_/

[>] Created By   : thewhiteh4t
 |---> Twitter   : https://twitter.com/thewhiteh4t
 |---> Community : https://twc1rcle.com/
[>] Version      : 1.1.7

[+] Target : https://www.example.com

[+] IP Address : 188.114.99.224

[!] Starting DNS Enumeration...

Traceback (most recent call last):
  File "/home/kali/FinalRecon/finalrecon.py", line 292, in <module>
    dnsrec(hostname, dserv, out_settings, data)
  File "/home/kali/FinalRecon/modules/dns.py", line 27, in dnsrec
    res.nameservers = [sv.strip() for sv in dns_servers.split(',')]
                                            ^^^^^^^^^^^^^^^^^
AttributeError: 'list' object has no attribute 'split'

**Comment by thewhiteh4t** [comment]
@Eduard123321 fixed, use `git pull` to update and try again

**Comment by thewhiteh4t** [comment]
thanks for catching this one
